Add app open ai
keboola/connection-docs pull request #464
Opened 2023-02-16 14:42 UTC by SgtMarmite

I have added app-open-ai docs. I have also created new category in the navbar "applications/other", since app-open-ai is not a trigger.

2023-02-20 08:08 UTC, SgtMarmite commented
tagging @bakobako

2023-02-20 09:45 UTC, bakobako requested changes

2023-02-20 09:45 UTC, bakobako commented on components/applications/ai/index.md
> +
I would add a short description of this section.
e.g.

AI applications are used to generate, process, or enrich data by custom models or 3rd Party AI API services. The following AI applications are available:


I would also add a very short description of what the OpenAI app does 
e.g.

- [OpenAI](/components/applications/ai/open-ai/) - Process input data with a custom prompt with OpenAI models

2023-02-20 10:40 UTC, bakobako commented on components/applications/ai/index.md
> +
@SgtMarmite tagging you

2023-02-20 11:31 UTC, SgtMarmite commented
@bakobako Added in https://github.com/keboola/connection-docs/pull/464/commits/e28c05237b07e3178b2746e23d90b6d5dda06080

2023-03-14 12:55 UTC, hhanova approved these changes
suggested UI changes :-) 
(Please create new screenshots when done. Thanks a lot!)

Screenshot #1
1. Provide a table containing columns with input data to be used in **a** prompt and other arbitrary columns which can be used as **a** primary key of the output table.
2. The application will query **the** Open AI service and store the result in the ABC column for each input.
3. extractor configuration => **Data Source Configuration**
4. Hide **data source** configuration settings
5. Sleep **T**ime

Screenshot #2
Pick from predefined models or enter a custom one. => **Select which type of model you want to use, either predefined or custom.**

Screenshot #3
1. Refer to **the** input column using placeholder xyz.
2. Za poslední větou chybí tečka.
3. You can enter multiple columns at once, e.g., ....

2023-04-06 09:50 UTC, SgtMarmite commented
@hhanova I have edited the UI and made new screenshots

2023-04-06 12:11 UTC, bakobako approved these changes

2023-04-06 12:12 UTC, merged