External tables are not supported info
keboola/connection-docs pull request #538
Opened 2023-11-13 09:47 UTC by romanbracinik

Jira issue(s): PROOF-XXX

Changes:

-

---

2023-11-13 11:48 UTC, jirkasemmler requested changes
dve veci
- `are not supported**,** and if the shared dataset contains such tables`
- strcil bych to do te sekce dole . Udelal bych to jako Notes: < seznam >
- je pak potreba udelat novy screenshot toho guidu

2023-11-13 13:17 UTC, romanbracinik commented
Neviewm ci som ten notes pochopil spravne datak davam screen, ale zas tak dobre to nevyzera :D
<img width="1080" alt="Screenshot 2023-11-13 at 14 16 42" src="https://github.com/keboola/connection-docs/assets/6448364/19f8fba3-5216-4485-a65a-d759c2a69376">

2023-11-13 22:33 UTC, jirkasemmler commented
no tak to se ty nase vykreslovaci styly moc nepredvedly... hele mrknu jsem na to a prijde mi nejlepsi asi toto , strcil jsem to do posledniho commitu.
![image](https://github.com/keboola/connection-docs/assets/13363655/68621213-d232-4d6d-9939-d5ddfd2ef288)

jen bacha, mas tam asi jeste stary screenshot (vzhledem k https://github.com/keboola/connection/pull/4709/commits/9f199c4fd748d3a77fabe0cb891fce979eaea545 )

2023-11-13 22:34 UTC, jirkasemmler requested changes
mrkni prosim na ten screenshot a rekni jak se tvaris na ty moje upravy

2023-11-14 08:02 UTC, romanbracinik commented
> mrkni prosim na ten screenshot a rekni jak se tvaris na ty moje upravy

super tak to vyzera dobre ja som pridal novy screen 18e846434b70ab74c556f55bab84e7dfb5600b45

2023-11-14 08:23 UTC, jirkasemmler approved these changes

2023-11-14 08:23 UTC, jirkasemmler commented
(davam approve, anglictinu jsem si checknul s GPT)

2023-12-01 11:45 UTC, merged