Init docs for Big Query Transformations
keboola/connection-docs pull request #568
Opened 2024-01-22 15:44 UTC by AdamVyborny

JIRA: https://keboola.atlassian.net/browse/PST-1153

2024-01-24 05:52 UTC, pavel-synek approved these changes
good in my perspective, but please check with Jirka Semmler as well.

2024-01-25 12:44 UTC, AdamVyborny commented
@jirkasemmler můžeš na to pls někdy mrknout za engg?

2024-01-25 14:12 UTC, jirkasemmler requested changes
jen tam prosim nekam zalinkuj ty nase limitace

2024-01-25 14:12 UTC, jirkasemmler commented on transformations/bigquery/index.md
> +## Limits
tady jsem to ted popisoval, jake to ma limity jeste ze strany kebooly https://help.keboola.com/storage/byodb/#bigquery-limitations

2024-01-25 14:28 UTC, jirkasemmler approved these changes

2024-01-25 14:29 UTC, merged